= Notes on DynamoDB using Java v2 SDK

== Introduction

There are two ways to interact with DynamoDB using the Java SDK.
Actually, there are three technically if you count the low level API.
Generally though, you will want to use one of the two higher level APIs.

The standard SDK approach relies on `HashMap<String, AttributeValue>`, where
the `AttributeValue` class is a container class used to manage the various
attribute types that can be supported by DynamoDB.

The other approach uses the new _Enhanced Client_ class to allow for object
mapping using annotations.

These examples show both approaches.

=== Standard SDK approach

This approach requires a bit more translation between how the data might be
represented within the application and how it is effectively marshalled or
unmarshalled to DynamoDB tables.

[source, java]
----
   public void putItem(String userId, Integer noteId, String note) {
        HashMap<String,AttributeValue> itemValues = new HashMap<>(); // <1>
        itemValues.put("UserId", AttributeValue.builder().s(userId).build()); // <2>
        itemValues.put("NoteId", AttributeValue.builder().n(noteId.toString()).build()); // <3>
        itemValues.put("Notes", AttributeValue.builder().s(note).build());
        PutItemRequest request = PutItemRequest.builder()
                .tableName(TABLE_NAME)
                .item(itemValues)
                .build();
----
<1> AttributeValue is a helper class provided by the DynamoDB SDK
<2> Passing a string in and marking as such
<3> Numeric values are passed in as String but marked as a numeric

=== Using the Enhanced Client