= Notes on DynamoDB using Java v2 SDK

== Introduction

There are two ways to interact with DynamoDB using the Java SDK.
Actually, there are three technically if you count the low level API.
Generally though, you will want to use one of the two higher level APIs.

The standard SDK approach relies on `HashMap<String, AttributeValue>`, where
the `AttributeValue` class is a container class used to manage the various
attribute types that can be supported by DynamoDB.

The other approach uses the new _Enhanced Client_ class to allow for object
mapping using annotations.

These examples show both approaches.

=== Standard SDK approach

This approach requires a bit more translation between how the data might be
represented within the application and how it is effectively marshalled or
unmarshalled to DynamoDB tables.

[source, java]
----
   public void putItem(String userId, Integer noteId, String note) {
        HashMap<String,AttributeValue> itemValues = new HashMap<>(); // <1>
        itemValues.put("UserId", AttributeValue.builder().s(userId).build()); // <2>
        itemValues.put("NoteId", AttributeValue.builder().n(noteId.toString()).build()); // <3>
        itemValues.put("Notes", AttributeValue.builder().s(note).build());
        PutItemRequest request = PutItemRequest.builder()
                .tableName(TABLE_NAME)
                .item(itemValues)
                .build();
----
<1> AttributeValue is a helper class provided by the DynamoDB SDK
<2> Passing a string in and marking as such
<3> Numeric values are passed in as String but marked as a numeric

Queries are also slightly more complicated as they may involve passing
in partial elements of the partition key as well as the sort key.

[source, java]
----
        HashMap<String, AttributeValue> attrValues = new HashMap<>();
        attrValues.put(":v_UserId", AttributeValue.builder().s(userId).build()); // <1>

        QueryRequest queryRequest = QueryRequest.builder()
                .tableName(TABLE_NAME)
                .keyConditionExpression("UserId = :v_UserId") // <2>
                .expressionAttributeValues(attrValues)
                .build();

----
<1> This is similar to a named query parameter we called 'v_UserId'
<2> The key condition expression allows some flexibility for comparison

=== Using the Enhanced Client

With the Enhanced Client, the repository implementation can become a bit
more sophisticated.
This is done by defining a container class representing the object data being stored.
In this case, a `NotesItem` class is defined that contains the attributes found in
the _Notes_ table.
Then, a series of annotations are used to designate the class as a DynamoDB bean class
and to mark the appropriate attributes as either _PartitionKey_ attribute or _SortKey_
attribute.
In addition, it is possible to map class field names to table attribute names, which can
be quite helpful when you want to decouple the implementation code from the DynamoDB
table definition.

[source, java]
----
@DynamoDbBean
public class NotesItem {
...
    @DynamoDbPartitionKey
    @DynamoDbAttribute("UserId")
    public String getUserId() {
        return this.userId;
    }

    @DynamoDbSortKey
    @DynamoDbAttribute("NoteId")
    public Integer getNoteId() {
        return this.noteId;
    }
...
}
----

=== Creating the DynamoDB table

To run these code samples, it will be necessary to create a table
You can do this via the AWS CLI quite easily from either Linux/MacOS or Windows.

NOTE: This is the same table definition used in Lab 4 of the _Developing on AWS_
course.

*Linux*
[source, bash]
----
aws dynamodb create-table \
  --table-name Notes \
  --attribute-definitions AttributeName=UserId,AttributeType=S AttributeName=NoteId,AttributeType=N \
  --key-schema AttributeName=UserId,KeyType=HASH AttributeName=NoteId,KeyType=RANGE \
  --provisioned-throughput ReadCapacityUnits=5,WriteCapacityUnits=5

----

*Windows*
[source, bash]
----
aws dynamodb create-table ^
  --table-name Notes ^
  --attribute-definitions AttributeName=UserId,AttributeType=S AttributeName=NoteId,AttributeType=N ^
  --key-schema AttributeName=UserId,KeyType=HASH AttributeName=NoteId,KeyType=RANGE ^
  --provisioned-throughput ReadCapacityUnits=5,WriteCapacityUnits=5

----

